version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci